# Generated by Django 5.2.12 on 2026-03-30 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('languages_used', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.project'),
        ),
    ]
